---
title: "Reproducible Research: Peer Assessment 1"

output: 
  html_document:
    keep_md: true
---
## Rao Bethamcharla

## Loading and preprocessing the data

csvfile <- "activity.csv"
if (!file.exists(csvfile)) {
  zipfile <- "repdata_data_activity.zip"
  if (!file.exists(zipfile)) {
    stop("Cannot find data files")
  } else {
    unzip(zipfile)
    if (!file.exists(csvfile)) {stop("Unzip Error")}
  }
}
# Load the data (i.e. read.csv())
data <- read.csv(csvfile)
# Process/transform the data (if necessary) into a format suitable for your analysis
# Get dates into better format
min<-as.character(data$interval%%100)
hr <-as.character(floor(data$interval/100))
hrmin <- paste(sep=":",hr,min,"00")
data$min <-min
data$hr  <-hr
data$time<-as.POSIXct(paste(as.character(data$date),hrmin))

## What is mean total number of steps taken per day?



## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
